### ISSUE TITLE
Pannello risultati ricerca dati anagrafici

### ISSUE THREAD

**Issue by Sazaky** [Sazaky/Gestionale#10]
In questo pannello dovranno risultare i dati inerenti il contatto ricercato
Qualifica
Indirizzo
Email
Numero telefono fisso
Numero telefono mobile
Note (nuovo)

**Comment by GiovanniMancini** [comment]
@Sazaky Qua potrebbe essere ua semplice lista letta dal database, forse non serve una ricerca. Tipo i contatti whatsapp
