### ISSUE TITLE
Al nuovo contatto nn funziona aggiungi visita

### ISSUE THREAD

**Issue by Sazaky** [Sazaky/Gestionale#53]

**Comment by GiovanniMancini** [comment]
Il bug si presenta quando l'id dell'informatore risulta non definito. es.

```
{"agent_id": undefined, "date": 2023-02-06T21:15:00.000Z, "doctor_id": 2, "note": "CIAO", "status": 1}
```

Poiché l'id è preso dalle visite, quando la lista delle visite è vuota si ottiene il bug
